#!/usr/bin/env node
/**
 * Renders the AUR package for `syncparty-bin`.
 *
 * Tauri's bundler cannot produce a pacman package — its Linux targets are
 * `deb`, `rpm`, and `appimage`, and nothing else — so the PKGBUILD is written
 * here and pushed to the AUR as its own repository.
 *
 * It is a `-bin` package sourcing the published `.deb`, which is ordinary AUR
 * practice and means Arch and Debian run the *same* binary: one artifact to
 * test rather than two. Building from source on the user's machine would pull
 * a Rust toolchain and Node in as `makedepends` and move every build failure
 * onto their machine; `docs/building.md` covers that case for anyone who
 * wants it.
 *
 * Both files are emitted from one definition below, because a PKGBUILD and a
 * .SRCINFO that disagree is the classic way an AUR package breaks — and
 * `makepkg --printsrcinfo`, the usual generator, only runs on Arch.
 *
 *   node scripts/aur-package.mjs --deb <path> --out <dir>
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function argument(name, fallback = null) {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1 || index === process.argv.length - 1) {
    if (fallback !== null) return fallback;
    throw new Error(`missing required argument --${name}`);
  }
  return process.argv[index + 1];
}

const debPath = argument("deb");
const outDir = argument("out", join(root, "packaging/aur/out"));

const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const sha256 = createHash("sha256").update(readFileSync(debPath)).digest("hex");
const debName = basename(debPath);
const debUrl = `https://github.com/Tahckn/syncparty/releases/download/v${version}/${debName}`;

/**
 * One definition, rendered into both files.
 *
 * `syncplay` is a hard dependency because it is the client the guest half
 * launches, and `pyside6`/`shiboken6` come with it because Arch ships them as
 * optdepends — a bare `pacman -S syncplay` installs a client with no GUI.
 *
 * A player has to be named too: Arch lists `mpv` and `vlc` as optdepends of
 * `syncplay`, so neither is guaranteed. `mpv` is the hard one because the app
 * prefers it; `vlc` stays optional.
 */
const pkg = {
  pkgname: "syncparty-bin",
  pkgver: version,
  pkgrel: "1",
  pkgdesc: "Synchronised movie nights, peer to peer",
  arch: ["x86_64"],
  url: "https://github.com/Tahckn/syncparty",
  license: ["MIT"],
  depends: [
    "webkit2gtk-4.1",
    "gtk3",
    "libayatana-appindicator",
    "syncplay",
    "pyside6",
    "shiboken6",
    "mpv",
  ],
  optdepends: [
    "vlc: alternative to mpv",
    "gnome-keyring: keep secrets in the keyring instead of a file",
  ],
  provides: ["syncparty"],
  conflicts: ["syncparty"],
  options: ["!strip", "!debug"],
  source: [`${debName}::${debUrl}`],
  // makepkg has no idea what to do with a .deb — it is an `ar` archive, not
  // one of the formats it unpacks — so extraction happens in package() below.
  noextract: [debName],
  sha256sums: [sha256],
};

function array(name, values) {
  return `${name}=(${values.map((value) => `'${value}'`).join(" ")})`;
}

const pkgbuild = `# Maintainer: Mert Emir <48881002+mertemr@users.noreply.github.com>
#
# Generated by scripts/aur-package.mjs — edit that, not this file.

pkgname=${pkg.pkgname}
pkgver=${pkg.pkgver}
pkgrel=${pkg.pkgrel}
pkgdesc='${pkg.pkgdesc}'
${array("arch", pkg.arch)}
url='${pkg.url}'
${array("license", pkg.license)}
${array("depends", pkg.depends)}
${array("optdepends", pkg.optdepends)}
${array("provides", pkg.provides)}
${array("conflicts", pkg.conflicts)}
${array("options", pkg.options)}
${array("source", pkg.source)}
${array("noextract", pkg.noextract)}
${array("sha256sums", pkg.sha256sums)}

package() {
  # The .deb already lays out /usr exactly as this package should: the binary,
  # the .desktop file (carrying MimeType=x-scheme-handler/syncparty, which is
  # what makes invite links work), the icons, and the bundled Syncplay server
  # under /usr/lib/syncparty. Unpacking it wholesale keeps Arch and Debian on
  # a byte-identical install rather than re-deriving the layout here.
  #
  # Two passes: the outer archive is \`ar\`, and data.tar.* inside it holds the
  # tree. bsdtar reads both and works out the compression on its own.
  bsdtar -xOf '${debName}' 'data.tar.*' | bsdtar -xpf - -C "\${pkgdir}"
}
`;

const srcinfo = [
  `pkgbase = ${pkg.pkgname}`,
  `\tpkgdesc = ${pkg.pkgdesc}`,
  `\tpkgver = ${pkg.pkgver}`,
  `\tpkgrel = ${pkg.pkgrel}`,
  `\turl = ${pkg.url}`,
  ...pkg.arch.map((value) => `\tarch = ${value}`),
  ...pkg.license.map((value) => `\tlicense = ${value}`),
  ...pkg.depends.map((value) => `\tdepends = ${value}`),
  ...pkg.optdepends.map((value) => `\toptdepends = ${value}`),
  ...pkg.provides.map((value) => `\tprovides = ${value}`),
  ...pkg.conflicts.map((value) => `\tconflicts = ${value}`),
  ...pkg.options.map((value) => `\toptions = ${value}`),
  ...pkg.source.map((value) => `\tsource = ${value}`),
  ...pkg.noextract.map((value) => `\tnoextract = ${value}`),
  ...pkg.sha256sums.map((value) => `\tsha256sums = ${value}`),
  "",
  `pkgname = ${pkg.pkgname}`,
  "",
].join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "PKGBUILD"), pkgbuild);
writeFileSync(join(outDir, ".SRCINFO"), srcinfo);

console.log(`Rendered ${pkg.pkgname} ${pkg.pkgver} into ${outDir}`);
console.log(`  source  ${pkg.source[0]}`);
console.log(`  sha256  ${sha256}`);
