// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyId } from "./DependencyId";
import type { Invite } from "./Invite";
import type { PreflightReport } from "./PreflightReport";
import type { RoomSnapshot } from "./RoomSnapshot";
import type { SessionState } from "./SessionState";

/**
 * Everything the frontend can be told about. Tagged so TypeScript gets a
 * discriminated union it can exhaustively match on.
 */
export type AppEvent = { "kind": "preflightCompleted", report: PreflightReport, } | { "kind": "installProgress", dependency: DependencyId, stage: string, 
/**
 * Absent when the underlying installer reports no percentage.
 */
percent: number | null, detail: string | null, } | { "kind": "sessionChanged", state: SessionState, } | { "kind": "roomUpdated", snapshot: RoomSnapshot, } | { "kind": "serverLog", line: string, isError: boolean, } | { "kind": "inviteReceived", invite: Invite, } | { "kind": "failed", errorKind: string, message: string, };
