// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";

export type AppSettings = { 
/**
 * `None` until onboarding completes.
 */
mode: AppMode | null, port: number, room: string, nickname: string, 
/**
 * BCP-47 tag; the UI ships `tr` and `en`.
 */
language: string, 
/**
 * Whether the host attaches a hidden client to read live room state.
 * Disabling it trades the rich panel for one fewer name in the user list.
 */
monitorEnabled: boolean, 
/**
 * Whether a setup screen with nothing to report should show itself.
 *
 * The check still runs on every launch — what this skips is the screen,
 * and only when every dependency is present. A machine that has lost one
 * still stops here, which is the property that makes the flag safe.
 */
skipSetupWhenReady: boolean, discordEnabled: boolean, 
/**
 * Programs the user pointed at by hand, keyed by dependency.
 *
 * Automatic detection covers installers and `PATH`, which misses
 * portable builds — an mpv zip extracted to some folder is invisible to
 * both. Rather than guess at where people keep those, this lets them say.
 */
executableOverrides: { [key in string]: string }, };
