// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for each dependency, shared with the frontend.
 */
export type DependencyId = "syncplayClient" | "mpv";
