// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightReport } from "./PreflightReport";
import type { SessionState } from "./SessionState";

export type DiagnosticsReport = { appVersion: string, operatingSystem: string, dependencies: PreflightReport, 
/**
 * This machine's address on the syncparty network.
 *
 * Absent until the first time it hosts, since only a host needs a stable
 * identity. Included because it is the one value that identifies a
 * machine when comparing notes about a party that would not connect.
 */
endpoint: string | null, session: SessionState, };
