// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoverFilter = { genreId: number | null, year: number | null, 
/**
 * A TMDB `sort_by` value verbatim (e.g. `"popularity.desc"`) — passed
 * straight through rather than modelled, since the set TMDB accepts
 * changes independently of this app.
 */
sortBy: string | null, minRating: number | null, };
