// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invite } from "./Invite";
import type { ServerState } from "./ServerState";

/**
 * Everything the host screen needs once a party is live.
 */
export type HostingInfo = { invite: Invite, inviteCode: string, deepLink: string, 
/**
 * Where the Syncplay server is listening, for the host's own client and
 * for diagnostics. Always on loopback — guests never see this.
 */
serverAddress: string, server: ServerState, monitorAttached: boolean, };
