// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A party, in the form a guest receives it.
 */
export type Invite = { 
/**
 * The host's iroh endpoint id — its public key, written out.
 *
 * This is the whole address. There is no host name, no IP and no port,
 * because the transport resolves the id to whatever route works right
 * now: a direct connection when hole punching succeeds, a relay when it
 * does not.
 */
endpoint: string, password: string, room: string, };
