// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieCandidate } from "./MovieCandidate";
import type { VoteParticipant } from "./VoteParticipant";
import type { VotePhase } from "./VotePhase";
import type { VoteResult } from "./VoteResult";

export type MovieVoteSnapshot = { id: string, phase: VotePhase, createdAt: bigint, 
/**
 * ISO 8601 date or date-time, already resolved to the host's timezone by
 * the frontend — `core` treats it as an opaque label and never parses
 * it. `None` means no movie night time was set.
 */
schedule: string | null, candidates: Array<MovieCandidate>, participants: Array<VoteParticipant>, 
/**
 * Set once the vote closes.
 */
result: VoteResult | null, };
