// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Genre } from "./Genre";
import type { MovieVideo } from "./MovieVideo";
import type { WatchProvider } from "./WatchProvider";

export type MovieDetails = { tmdbId: bigint, title: string, originalTitle: string, poster: string | null, backdrop: string | null, releaseDate: string | null, runtimeMinutes: number | null, genres: Array<Genre>, rating: number, voteCount: bigint, overview: string, trailer: MovieVideo | null, 
/**
 * Never used to stream anything — only to point a person at wherever
 * TMDB (via JustWatch) says the movie is available, per JustWatch's
 * attribution requirement.
 */
watchProviders: Array<WatchProvider>, watchLink: string | null, };
