// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieCandidate = { tmdbId: bigint, title: string, poster: string | null, releaseDate: string | null, overview: string | null, genres: Array<string>, rating: number, };
