// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One night: when it ran, what was on, and who was in the room.
 *
 * Separate from `SessionHistoryEntry`, which is a *vote's* record — a party
 * can run without a vote ever being held, and a vote's clock starts when the
 * ballot was drafted rather than when anyone actually sat down.
 */
export type PartyLogEntry = { id: string, startedAt: bigint, 
/**
 * `None` while the party is still running.
 */
endedAt: bigint | null, movieTmdbId: bigint | null, movieTitle: string | null, moviePoster: string | null, 
/**
 * Everyone seen in the room over the whole night, not just whoever was
 * still there at the end — people drop out of a call and come back.
 */
participants: Array<string>, };
