// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind } from "./PathKind";

/**
 * One live connection, and how it turned out to be carried.
 */
export type PeerPath = { peer: string, kind: PathKind, 
/**
 * The selected path's far address, as iroh reports it.
 */
remote: string | null, rttMs: bigint | null, };
