// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which player an automatic install should fetch.
 *
 * Only the player has more than one source, so this is the only dependency
 * whose install takes an argument. Detection is unaffected: `find_player`
 * prefers mpv when both are present, whichever one was installed from here.
 */
export type PlayerChoice = "mpv" | "vlc";
