// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One relay this endpoint has been assigned, and whether it is usable.
 */
export type RelayHealth = { url: string, connected: boolean, lastError: string | null, };
