// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieVoteSnapshot } from "./MovieVoteSnapshot";

export type SessionHistoryEntry = { id: string, startedAt: bigint, endedAt: bigint | null, snapshot: MovieVoteSnapshot, };
