// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";

/**
 * A partial settings update. Absent fields are left alone, so the UI can send
 * just the toggle the user touched.
 *
 * `#[ts(optional)]` matters here: without it every field generates as
 * `T | null`, which would force the frontend to spell out all seven on every
 * call and defeat the point of a patch.
 */
export type SettingsPatch = { mode?: AppMode, port?: number, room?: string, nickname?: string, language?: string, monitorEnabled?: boolean, skipSetupWhenReady?: boolean, discordEnabled?: boolean, };
