// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerPath } from "./PeerPath";
import type { RelayHealth } from "./RelayHealth";

/**
 * What the transport can say about itself right now.
 *
 * Assembled from a live endpoint, so every field is measured rather than
 * configured — which is the point. Nothing here is read from settings, and
 * there is no address for the user to have got wrong.
 */
export type TransportReport = { 
/**
 * This machine's address on the syncparty network.
 */
endpointId: string, 
/**
 * The addresses iroh worked out for this machine, including any public
 * one a relay observed. Not a setting — these are discovered.
 */
addresses: Array<string>, 
/**
 * Whether a discovered address falls inside the carrier-grade NAT range.
 *
 * `None` when no public IPv4 was discovered at all, which is a different
 * statement from "not behind CGNAT" and must not be shown as one.
 */
behindCarrierNat: boolean | null, relays: Array<RelayHealth>, 
/**
 * Live connections. Empty when no party is running, which is why the
 * screen has to say so rather than reading it as "nobody connected".
 */
peers: Array<PeerPath>, };
