// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePolicy = { 
/**
 * Whether to look for a new release at all.
 */
checks: boolean, 
/**
 * Whether the app may download and install what it finds.
 *
 * False on Linux, where the answer is "your package manager does that".
 */
selfInstalls: boolean, };
