// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSummary } from "./MovieSummary";

/**
 * One person's own marks on a movie — a favourite, a "seen it", or both.
 *
 * The summary is stored alongside the flags rather than looked up again:
 * a favourites list or a watched grid is a list of posters, and re-fetching
 * every one of them from TMDB to draw a screen the user has already seen
 * turns a local list into a network round trip per movie.
 */
export type UserMovie = { movie: MovieSummary, favorite: boolean, watched: boolean, 
/**
 * When the flags last changed. Sorts a list newest first.
 */
markedAt: bigint, };
