// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a vote is in its lifecycle.
 *
 * ```text
 * Draft (candidates editable) -> Open (locked, votes accepted) -> Completed
 *                                                               -> Cancelled
 * ```
 */
export type VotePhase = "draft" | "open" | "completed" | "cancelled";
