// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateTally } from "./CandidateTally";

export type VoteResult = { tally: Array<CandidateTally>, 
/**
 * `Some` once a single winner is settled — either nobody tied for the
 * top, or the host broke a tie. `None` while a tie is waiting on the
 * host to resolve it.
 */
winner: bigint | null, 
/**
 * The tmdb ids tied for first. Non-empty only while `winner` is `None`.
 */
tied: Array<bigint>, };
