// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParticipationStatus } from "./ParticipationStatus";

export type VoteParticipant = { 
/**
 * Whoever this is, keyed by their endpoint id as a string — or the
 * literal `"host"` for the host's own entry, which has no guest
 * connection to key on.
 */
peer: string, displayName: string, participation: ParticipationStatus | null, selectedMovie: bigint | null, respondedAt: bigint | null, };
