// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchedMovie = { tmdbId: bigint, title: string, sessionId: string, watchedAt: bigint, participants: Array<string>, };
